name: CI Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_DEV_HOST }}" >> $GITHUB_ENV
            echo "VPS_PORT=2222" >> $GITHUB_ENV
            echo "VPS_USER=${{ secrets.VPS_DEV_USER }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.SSH_DEV_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "BRANCH=develop" >> $GITHUB_ENV
            sed -i "s|{{SUBDOMAIN}}|gifto.local|g" docker-compose.yml
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_PROD_HOST }}" >> $GITHUB_ENV
            echo "VPS_PORT=22" >> $GITHUB_ENV
            echo "VPS_USER=${{ secrets.VPS_PROD_USER }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.SSH_PROD_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
            sed -i "s|{{SUBDOMAIN}}|gifto|g" docker-compose.yml
          else
            echo "No deployment for this event."
            exit 0
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.VPS_HOST }}
          port: ${{ env.VPS_PORT }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/gifto-front
            cd /opt/gifto-front
            if [ ! -d ".git" ]; then
              git clone -b $BRANCH git@github.com:sosthenenouebissi/gifto-front.git .
            else
              git fetch origin
              git checkout $BRANCH
              git pull origin $BRANCH
            fi
            sudo docker compose down
            sudo docker compose up -d --build
