name: CI Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - develop
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: "/opt/gifto-front"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_DEV_HOST }}" >> $GITHUB_ENV
            echo "VPS_PORT=2222" >> $GITHUB_ENV
            echo "VPS_USER=${{ secrets.VPS_DEV_USER }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.SSH_DEV_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "BRANCH=develop" >> $GITHUB_ENV
            echo "SUBDOMAIN=Host(`gifto.local.sosthyone.fr`)" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VPS_HOST=${{ secrets.VPS_PROD_HOST }}" >> $GITHUB_ENV
            echo "VPS_PORT=22" >> $GITHUB_ENV
            echo "VPS_USER=${{ secrets.VPS_PROD_USER }}" >> $GITHUB_ENV
            echo "SSH_PRIVATE_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.SSH_PROD_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "BRANCH=main" >> $GITHUB_ENV
            echo "SUBDOMAIN=Host(`gifto.sosthyone.fr`) || Host(`gifto.sosthyone.com`)" >> $GITHUB_ENV
          else
            echo "No deployment for this event."
            exit 0
          fi

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.VPS_HOST }}
          port: ${{ env.VPS_PORT }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          envs: DEPLOY_PATH, BRANCH, SUBDOMAIN
          script: |
            rm -rf $DEPLOY_PATH
            echo "Cloning repository into $DEPLOY_PATH"
            git clone -b "$BRANCH" git@github.com:sosthenenouebissi/gifto-front.git "$DEPLOY_PATH"
            cd $DEPLOY_PATH
            sed -i "s|{{SUBDOMAIN}}|$SUBDOMAIN|g" docker-compose.yml
            cat docker-compose.yml
            docker compose down
            docker compose up -d --build
